# Generated by Django 4.2.7 on 2025-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_submitted_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
