# Generated by Django 4.2.7 on 2025-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('Rookie', 'Rookie'), ('Novice', 'Novice'), ('Experienced', 'Experienced'), ('Expert', 'Expert'), ('Master', 'Master')], default='Rookie', max_length=20),
        ),
    ]
